export const packagesdata = [
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "sdadmcnadkmcvdnkcmvdskcmdk",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "sdadmcnadkmcvdnkcmvdskcmdk",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "sdadmcnadkmcvdnkcmvdskcmdk",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "sdadmcnadkmcvdnkcmvdskcmdk",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "sdadmcnadkmcvdnkcmvdskcmdk",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "sdadmcnadkmcvdnkcmvdskcmdk",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "sdadmcnadkmcvdnkcmvdskcmdk",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "sdadmcnadkmcvdnkcmvdskcmdk",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "sdadmcnadkmcvdnkcmvdskcmdk",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
  {
    package: "3proxy",
    version: "0.9.4",
    category: "Lorem ipsum",
    description: "Tiny free proxy server",
    repository: "archstrike",
  },
];